#!/usr/bin/env python3
"""
tools/mkfont.py -- convert GNU Unifont .hex data into vtirc-ng's VTUF glyph format.

Outputs
  src/fonts/unifont_embed.bi   FreeBASIC byte array with the embedded subset
                               (scripts most IRC users need; compiled into the exe)
  fonts/vtirc-ng.vtuf          every glyph in the .hex file (optional runtime file,
                               shipped next to the executable for CJK etc.)

VTUF layout (all integers little-endian)
  0   char[4]  "VTUF"
  4   u16      version (1)
  6   u16      glyph height in pixels (16)
  8   u32      glyph count N
  12  N x { u32 key, u32 offset }     key = codepoint | (width_cells << 24)
                                      sorted by codepoint; offset relative to
                                      the start of the bitmap area
  12+8N        bitmaps: width 1 -> 16 bytes (1 byte/row), width 2 -> 32 bytes (2 bytes/row)

Usage
  tools/mkfont.py <unifont_all.hex[.gz]> <unifont-combining.txt>
"""
import gzip
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Ranges compiled into the executable. Everything else comes from the optional
# fonts/vtirc-ng.vtuf file.
EMBED_RANGES = [
    (0x00A0, 0x036F),   # Latin-1 supplement, Latin extended A/B, IPA, spacing + combining marks
    (0x0370, 0x03FF),   # Greek
    (0x0400, 0x052F),   # Cyrillic + supplement
    (0x0530, 0x058F),   # Armenian
    (0x0590, 0x05FF),   # Hebrew
    (0x0600, 0x06FF),   # Arabic
    (0x0E00, 0x0E7F),   # Thai
    (0x10A0, 0x10FF),   # Georgian
    (0x1E00, 0x1FFF),   # Latin extended additional (Vietnamese), Greek extended
    (0x2000, 0x2BFF),   # punctuation, super/subscripts, currency, letterlike, arrows, math,
                        # technical, enclosed, box drawing, blocks, shapes, symbols, dingbats
    (0x3000, 0x303F),   # CJK symbols and punctuation
    (0xFB00, 0xFB4F),   # alphabetic presentation forms (Hebrew)
    (0xFE70, 0xFEFF),   # Arabic presentation forms B (used by Arabic shaping)
    (0xFF01, 0xFF60),   # fullwidth ASCII variants
    (0xFFFD, 0xFFFD),   # replacement character
    (0x1F000, 0x1F02F), # mahjong / domino (small)
    (0x1F300, 0x1F64F), # misc symbols and pictographs, emoticons
    (0x1F680, 0x1F6FF), # transport and map symbols
    (0x1F900, 0x1F9FF), # supplemental symbols and pictographs
    (0x1FA70, 0x1FAFF), # symbols and pictographs extended-A
]


def load_hex(path):
    opener = gzip.open if str(path).endswith(".gz") else open
    glyphs = {}
    with opener(path, "rt", encoding="ascii") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_s, bits = line.split(":", 1)
            cp = int(cp_s, 16)
            if len(bits) == 32:
                width = 1
            elif len(bits) == 64:
                width = 2
            else:
                continue
            glyphs[cp] = (width, bytes.fromhex(bits))
    return glyphs


def load_combining(path):
    comb = set()
    with open(path, encoding="ascii") as f:
        for line in f:
            line = line.strip()
            if line and ":" in line:
                comb.add(int(line.split(":", 1)[0], 16))
    return comb


def pack(glyphs):
    cps = sorted(glyphs)
    index = bytearray()
    bitmaps = bytearray()
    for cp in cps:
        width, data = glyphs[cp]
        index += struct.pack("<II", cp | (width << 24), len(bitmaps))
        bitmaps += data
    header = b"VTUF" + struct.pack("<HHI", 1, 16, len(cps))
    return header + bytes(index) + bytes(bitmaps)


def in_embed(cp):
    return any(lo <= cp <= hi for lo, hi in EMBED_RANGES)


CHUNK = 16384   # fbc 1.10.1 crashes on a single initializer of a few 100k elements


def write_bi(blob, path, count):
    lines = [
        "' -----------------------------------------------------------------------------",
        "' src/fonts/unifont_embed.bi -- GENERATED by tools/mkfont.py, do not edit.",
        "' Embedded subset of GNU Unifont 17.0.05 in VTUF format (%d glyphs, %d bytes)." % (count, len(blob)),
        "' Unifont: GPLv2+ with the GNU font embedding exception, or SIL OFL 1.1.",
        "' See fonts/UNIFONT-LICENSE.txt.",
        "' Stored as %d-byte chunks (fbc cannot parse one huge initializer);" % CHUNK,
        "' vtirc_unifont_embed_blob() joins them into one contiguous block.",
        "' -----------------------------------------------------------------------------",
        '#Include Once "crt/string.bi"',
        "Const VTIRC_UNIFONT_EMBED_LEN = %d" % len(blob),
    ]
    chunks = [blob[i:i + CHUNK] for i in range(0, len(blob), CHUNK)]
    for ci, ch in enumerate(chunks):
        lines.append("Dim Shared vtirc_uf_c%d(0 To %d) As UByte = { _" % (ci, len(ch) - 1))
        for i in range(0, len(ch), 128):
            part = ",".join(str(b) for b in ch[i:i + 128])
            sep = "," if i + 128 < len(ch) else ""
            lines.append("    " + part + sep + " _")
        lines.append("}")
    lines += [
        "",
        "Function vtirc_unifont_embed_blob() As UByte Ptr",
        "    Static blob As UByte Ptr",
        "    If blob <> 0 Then Return blob",
        "    blob = Allocate(VTIRC_UNIFONT_EMBED_LEN)",
        "    If blob = 0 Then Return 0",
    ]
    for ci, ch in enumerate(chunks):
        lines.append("    memcpy(blob + %d, @vtirc_uf_c%d(0), %d)" % (ci * CHUNK, ci, len(ch)))
    lines += ["    Return blob", "End Function"]
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    glyphs = load_hex(sys.argv[1])
    combining = load_combining(sys.argv[2])

    full = pack(glyphs)
    emb = {cp: g for cp, g in glyphs.items() if in_embed(cp)}
    small = pack(emb)

    (ROOT / "fonts").mkdir(exist_ok=True)
    (ROOT / "src" / "fonts").mkdir(parents=True, exist_ok=True)
    (ROOT / "fonts" / "vtirc-ng.vtuf").write_bytes(full)
    write_bi(small, ROOT / "src" / "fonts" / "unifont_embed.bi", len(emb))
    write_width_table(ROOT / "src" / "fonts" / "unicode_width.bi", combining)

    print("full: %d glyphs, %d bytes" % (len(glyphs), len(full)))
    print("embedded: %d glyphs, %d bytes" % (len(emb), len(small)))


def ranges_of(pred, lo=0, hi=0x10FFFF):
    out = []
    start = None
    for cp in range(lo, hi + 1):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, hi))
    return out


def write_width_table(path, combining):
    """Display-width ranges (terminal wcwidth semantics) from Python's unicodedata."""
    import unicodedata as ud

    def zero(cp):
        if cp in combining:
            return True
        if 0x1160 <= cp <= 0x11FF:          # Hangul medial vowels / final consonants
            return True
        if cp in (0x200B, 0x200C, 0x200D, 0x2060, 0xFEFF):
            return True
        if 0xFE00 <= cp <= 0xFE0F or 0xE0100 <= cp <= 0xE01EF:   # variation selectors
            return True
        cat = ud.category(chr(cp))
        return cat in ("Mn", "Me") or (cat == "Cf" and cp != 0x00AD)

    def wide(cp):
        return ud.east_asian_width(chr(cp)) in ("W", "F")

    zr = ranges_of(zero, 0x300)
    wr = ranges_of(wide, 0x1100)
    lines = [
        "' -----------------------------------------------------------------------------",
        "' src/fonts/unicode_width.bi -- GENERATED by tools/mkfont.py, do not edit.",
        "' Display width ranges (Unicode %s via Python unicodedata)." % ud.unidata_version,
        "' zero-width: combining / format characters; wide: East Asian Wide/Fullwidth.",
        "' -----------------------------------------------------------------------------",
        "Const UW_ZERO_N = %d" % len(zr),
        "Const UW_WIDE_N = %d" % len(wr),
    ]

    def arr(name, rngs):
        flat = []
        for a, b in rngs:
            flat += [a, b]
        lines.append("Dim Shared %s(0 To %d) As ULong = { _" % (name, len(flat) - 1))
        for i in range(0, len(flat), 12):
            chunk = ",".join("&h%X" % v for v in flat[i:i + 12])
            sep = "," if i + 12 < len(flat) else ""
            lines.append("    " + chunk + sep + " _")
        lines.append("}")

    arr("uw_zero", zr)
    arr("uw_wide", wr)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
